import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/layout/Navbar";
import Leaderboard from "@/components/social/Leaderboard";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning attribute="class">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="min-h-screen bg-black text-white selection:bg-red-600/30">
            <Navbar />
            <main className="container mx-auto grid grid-cols-10 gap-8 py-8 px-4 lg:px-0">
              {/* Left Section (70%): Standard Scrolling Behavior */}
              <section className="col-span-10 lg:col-span-7 space-y-12">
                {children}
              </section>

              {/* Right Section (30%): Fixed/Sticky Behavior */}
              <aside className="hidden lg:block lg:col-span-3">
                <div className="sticky top-28 h-[calc(100vh-120px)] overflow-y-auto no-scrollbar">
                  <Leaderboard />
                </div>
              </aside>
            </main>
            {/* <Footer /> */}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
