import { Camp } from "@/types/camp";

export const MOCK_CAMPS: Camp[] = [
    {
      id: "1",
      title: "Himalayan Winter Survival",
      environment: "Land",
      specialization: "Physical",
      location: "Leh, Ladakh",
      date: "12 - 20March",
      status: "Registrations Open",
      image: "https://images.unsplash.com/photo-1519904981063-b0cf448d479e?auto=format&fit=crop&q=80&w=800",
      price: "23,999",
      seatsLeft: "10",
      totalSeats: "20",
    },
    {
      id: "2",
      title: "High-Altitude HALO Prep",
      environment: "Air",
      specialization: "Mental",
      location: "Pondicherry, IN",
      date: "5 April",
      status: "Live",
      image: "https://images.unsplash.com/photo-1664494130837-14e0473ed284?q=80&w=2670&auto=format&fit=crop&q=80&w=800",
      price: "19,999",
      seatsLeft: "5",
      totalSeats: "10",
    },
    {
      id: "3",
      title: "Deep Sea Tactical Breath-Hold",
      environment: "Water",
      specialization: "Medical",
      location: "Netrani, IN",
      date: "22 - 25 April",
      status: "Upcoming",
      image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=800",
      price: "31,999",
      seatsLeft: "5",
      totalSeats: "10",
    },
    {
      id: "4",
      title: "Urban Evasion & Survival",
      environment: "Land",
      specialization: "Mental",
      location: "Mumbai, IN",
      date: "10 May",
      status: "Upcoming",
      image: "https://images.unsplash.com/photo-1502134249126-9f3755a50d78?auto=format&fit=crop&q=80&w=800",
      price: "12,999",
      seatsLeft: "5",
      totalSeats: "10",
    },
    {
      id: "7",
      title: "Lost my buddy",
      environment: "Spirit Roads",
      specialization: "Spirit Roads",
      location: "Bengaluru, KA",
      date: "15th June",
      status: "Open",
      image: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&q=80&w=800",
      price: "18,500", // Fixed price
      seatsLeft: "12",
      totalSeats: "18",
    },
    {
      id: "8",
      title: "Dinner at my home",
      environment: "Spirit Roads",
      specialization: "Spirit Roads",
      location: "Chennai, TN",
      date: "20th July",
      status: "Open",
      image: "https://images.unsplash.com/photo-1569435998017-abb5d562dedf?auto=format&fit=crop&q=80&w=800",
      price: "35,000", // Fixed price
      seatsLeft: "7",
      totalSeats: "12",
    },
    {
      id: "9",
      title: "50 is the new 20",
      environment: "Spirit Roads",
      specialization: "Spirit Roads",
      location: "Hyderabad, Telangana",
      date: "25th August",
      status: "Open",
      image: "https://images.unsplash.com/photo-1610070835951-156b6921281d?auto=format&fit=crop&q=80&w=800",
      price: "20,000", // Fixed price
      seatsLeft: "9",
      totalSeats: "15",
    },
    {
      id: "10",
      title: "Stories from the field",
      environment: "Spirit Roads",
      specialization: "Spirit Roads",
      location: "Delhi, Delhi",
      date: "30th September",
      status: "Open",
      image: "https://images.unsplash.com/photo-1551847609-5aaf21a58ebc?auto=format&fit=crop&q=80&w=800",
      price: "28,000", // Fixed price
      seatsLeft: "6",
      totalSeats: "10",
    }
  ];

